name:                image-vips
version:             0.1.0.0
github:              Lupino/image-vips
license:             BSD3
author:              Li Meng Jun
maintainer:          lmjubuntu@gmail.com
copyright:           MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Lupino/image-vips#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src
  exposed-modules:
  - VipsImage
  dependencies:
  - inline-c
  - vector

  extra-libraries:
  - vips
  - gobject-2.0
  - glib-2.0
  - intl

  include-dirs:
  - /usr/local/Cellar/vips/8.6.0/include
  - /usr/local/Cellar/libgsf/1.14.42/include/libgsf-1
  - /usr/local/Cellar/fftw/3.3.6-pl2/include
  - /usr/local/Cellar/orc/0.4.28/include/orc-0.4
  - /usr/local/Cellar/little-cms2/2.9/include
  - /usr/local/Cellar/poppler/0.62.0/include/poppler/glib
  - /usr/local/Cellar/poppler/0.62.0/include/poppler
  - /usr/local/Cellar/librsvg/2.40.19/include/librsvg-2.0
  - /usr/local/Cellar/gdk-pixbuf/2.36.11/include/gdk-pixbuf-2.0
  - /usr/local/Cellar/libpng/1.6.34/include/libpng16
  - /usr/local/Cellar/cairo/1.14.10/include/cairo
  - /usr/local/Cellar/pixman/0.34.0_1/include/pixman-1
  - /usr/local/Cellar/pango/1.40.14/include/pango-1.0
  - /usr/local/Cellar/harfbuzz/1.7.2_1/include/harfbuzz
  - /usr/local/Cellar/graphite2/1.3.10/include
  - /usr/local/Cellar/pango/1.40.14/include/pango-1.0
  - /usr/local/Cellar/fontconfig/2.12.6/include
  - /usr/local/opt/freetype/include/freetype2
  - /usr/local/Cellar/libtiff/4.0.9/include
  - /usr/local/Cellar/libpng/1.6.34/include/libpng16
  - /usr/local/Cellar/libexif/0.6.21/include
  - /usr/local/Cellar/glib/2.54.2/include/glib-2.0
  - /usr/local/Cellar/glib/2.54.2/lib/glib-2.0/include
  - /usr/local/opt/gettext/include
  - /usr/local/Cellar/pcre/8.41/include
  - /usr/include/libxml2
  extra-lib-dirs:
  - /usr/local/Cellar/vips/8.6.0/lib
  - /usr/local/Cellar/glib/2.54.2/lib
  - /usr/local/opt/gettext/lib


executables:
  image-vips:
    main:                Main.hs
    source-dirs:         app
    cc-options:
    - -Wall
    ghc-options:
    - -Wall
    dependencies:
    - optparse-applicative
    - image-vips
    - scotty
    - text
    - warp
    - data-default-class
    - streaming-commons
    - http-types
    - wai

    - filepath
    - directory
    - mime-types
